const URL_SPLIT_TOKEN = '?';
const PARAMETER_SPLIT_TOKEN = '&';
const ARRAY_PARAMETER_JOIN_TOKEN = ',';
export { URL_SPLIT_TOKEN, PARAMETER_SPLIT_TOKEN, ARRAY_PARAMETER_JOIN_TOKEN };
//# sourceMappingURL=constants.js.map