declare const URL_SPLIT_TOKEN = "?";
declare const PARAMETER_SPLIT_TOKEN = "&";
declare const ARRAY_PARAMETER_JOIN_TOKEN = ",";
export { URL_SPLIT_TOKEN, PARAMETER_SPLIT_TOKEN, ARRAY_PARAMETER_JOIN_TOKEN };
